#!/bin/bash
set -o errexit

# This is the install directory, edit it if you wish
INSTALL_DIR="/var/lib/txircd"

# This is where the config file lives, edit it if you wish
CONF_FILE="/etc/txircd.yaml"

# Info for the user to run txircd as. This user will be created if it doesn't exist.
RUN_USER="txircd"

# If this is "true", set up the service to run on boot.
START_ON_BOOT="true"


TO_INSTALL=(twisted txircd)
SAMPLE_CONF="txircd.yaml"
UPSTART_FILE="/etc/init/txircd.conf"
SYSTEMD_FILE="/etc/systemd/system/txircd.service"

if [ "$#" -lt 1 ]; then
	echo "Please don't run this script manually - use either install.upstart"
	echo "or install.systemd, depending on your system."
	exit 1
fi
INIT_TYPE="$1"

# cd to location of this script
cd $(dirname $(readlink -f "$0"))

# create user if it doesn't exist
if ! id -u "$RUN_USER" >/dev/null 2>&1; then
	echo "Creating user: $RUN_USER"
	useradd --comment "An irc server" \
	        --home-dir "$INSTALL_DIR" \
	        --user-group \
	        --system \
	        --shell "/bin/false" \
	        "$RUN_USER"
fi

if [ -e "$INSTALL_DIR" ]; then
	echo "Clearing existing files"
    for path in "${TO_INSTALL[@]}"; do
    	rm -rf "$INSTALL_DIR/$path"
    done
else
    echo "Creating the virtualenv"
    mkdir -p "$INSTALL_DIR"
    virtualenv "$INSTALL_DIR"
fi

echo "Installing dependencies"
"$INSTALL_DIR/bin/pip" install -r requirements.txt

echo "Installing txircd"
cp -r "${TO_INSTALL[@]}" "$INSTALL_DIR"
[ -f "$CONF_FILE" ] || install -m 644 "$SAMPLE_CONF" "$CONF_FILE"
# fix file permissions - txircd assumes the local dir is writable
chown -R "$RUN_USER:" "$INSTALL_DIR"

echo "Setting up service"
case "$INIT_TYPE" in
	"upstart")
		ON_BOOT_STANZA="start on filesystem"
		[ "$START_ON_BOOT" == "true" ] || ON_BOOT_STANZA="# $ON_BOOT_STANZA"
		# write the upstart config
		cat > "$UPSTART_FILE" <<-EOF
		description "txircd: A modular irc server"

		$ON_BOOT_STANZA
		stop on runlevel [06]

		# Respawn it if the process exits
		respawn

		# log stdout/err to /var/log/upstart/txircd.log
		console log

		# run as user
		setuid $RUN_USER

		chdir "$INSTALL_DIR"
		exec "$INSTALL_DIR/bin/twistd" -n txircd --config "$CONF_FILE"
		EOF
		chmod 644 "$UPSTART_FILE"
		;;
	"systemd")
		# write the systemd unit file
		cat > "$SYSTEMD_FILE" <<-EOF
		[Unit]
		Description=txircd: A modular irc server

		[Service]
		WorkingDirectory=$INSTALL_DIR
		ExecStart=$INSTALL_DIR/bin/twistd -n txircd --config "$CONF_FILE"
		User=$RUN_USER
		Restart=on-failure

		[Install]
		WantedBy=multi-user.target
		EOF
		chmod 644 "$SYSTEMD_FILE"
		[ "$START_ON_BOOT" == "true" ] && systemctl enable txircd
		;;
	*)
		echo "WARNING: Unknown init system \"$INIT_SYSTEM\" - cannot set up service"
		;;
esac

echo "Done"
